# Generated by Django 4.0.4 on 2022-06-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_chead0_blogpost_chead1_blogpost_chead2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
